# Generated by Django 2.2.2 on 2019-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64, verbose_name='主机名')),
                ('cloud_sn', models.CharField(max_length=128, verbose_name='云厂商sn')),
                ('host_type', models.SmallIntegerField(choices=[(0, 'web服务器'), (1, 'mysql服务器'), (2, 'redis服务器'), (3, 'mongodb服务器')], verbose_name='服务器类型')),
                ('pub_ip1', models.GenericIPAddressField(blank=True, null=True)),
                ('pub_ip2', models.GenericIPAddressField(blank=True, null=True)),
                ('pri_ip1', models.GenericIPAddressField(blank=True, null=True)),
                ('pri_ip2', models.GenericIPAddressField(blank=True, null=True)),
                ('cpu_num', models.DecimalField(decimal_places=10, max_digits=256)),
                ('mem_total', models.FloatField()),
                ('disk_total1', models.FloatField()),
                ('disk_total2', models.FloatField()),
                ('c_time', models.DateTimeField(verbose_name='资产录入时间')),
                ('u_time', models.DateTimeField(verbose_name='最近更新时间')),
                ('is_deleted', models.SmallIntegerField(verbose_name='是否已下架')),
                ('memo', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '服务器',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128)),
                ('is_deleted', models.SmallIntegerField(verbose_name='业务是否下线')),
            ],
            options={
                'verbose_name': '业务线',
            },
        ),
        migrations.CreateModel(
            name='Asset_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_avg', models.FloatField()),
                ('cpu_used', models.FloatField()),
                ('mem_used', models.FloatField()),
                ('dist_used', models.FloatField()),
                ('host_name', models.ForeignKey(on_delete=False, to='cmdb.Assets')),
            ],
            options={
                'verbose_name': '服务器资源状态',
            },
        ),
    ]
