# Generated by Django 2.2.2 on 2019-10-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='c_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='资产录入时间'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='cpu_num',
            field=models.DecimalField(decimal_places=10, default=4, max_digits=256),
        ),
        migrations.AlterField(
            model_name='assets',
            name='disk_total2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assets',
            name='host_type',
            field=models.SmallIntegerField(choices=[(0, 'web服务器'), (1, 'mysql服务器'), (2, 'redis服务器'), (3, 'mongodb服务器')], default=0, verbose_name='服务器类型'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='是否已下架'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='mem_total',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='assets',
            name='u_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00', verbose_name='最近更新时间'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_deleted',
            field=models.SmallIntegerField(default=0, verbose_name='业务是否下线'),
        ),
    ]
